name: 'S3 Zip Upload for CodeDeploy'
description: 'Creates a zip file and uploads it to S3, and can also upload individual files. It works on both Linux and Windows'
author: 'Stijn Raeymaekers'
repository: 'https://github.com/alexshively/s3-zip-upload-for-codedeploy'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'node16'
  main: 'release/index.js'
dependencies:
  - '@actions/core'
  - '@aws-sdk/client-s3'
  - 'archiver'
  - 'fs'
  - 'path'
tags:
  - 's3'
  - 'zip'
  - 'upload'
  - 'windows'
  - 'linux'
  - 'codedeploy'
  - 'lambda'
